### ISSUE TITLE
Failed to resolve 'vue-class-component' from './node_modules/s-vuex-class/lib/bindings.js'

### ISSUE THREAD

**Issue by furstenheim** [gschafra/parcel-vue-typescript-boilerplate#39]
Sadly it seems that the dependencies are not working as expected :/
```
🚨 Build failed.

@parcel/core: Failed to resolve 'vue-class-component' from './node_modules/s-vuex-class/lib/bindings.js'

  /home/gabi/Gabi/apps-own/jirush/node_modules/s-vuex-class/lib/bindings.js:1:33
  > 1 | import { createDecorator } from 'vue-class-component';
  >   |                                 ^^^^^^^^^^^^^^^^^^^^^
    2 | import { mapState, mapGetters, mapActions, mapMutations } from 'vuex';
    3 | export var State = createBindingHelper('computed', mapState);

@parcel/resolver-default: Cannot find module 'vue-class-component'
💡 Did you mean 'vuex-class-modules'?

```

**Comment by gschafra** [comment]
Hi @furstenheim, this repo is quite experimental and therefore quite unstable 😉. Since vue class components are deprecated (see https://github.com/vuejs/vue-class-component/issues/584), I'm planned to switch to https://github.com/facing-dev/vue-facing-decorator or https://github.com/Haixing-Hu/vue3-class-component. Unfortunately my last commit on this was quite incomplete, leaving the code in a complete defect state, sorry. I'll try to fix this the next few weeks...
